specVersion: 1.0.0
name: subquery-network-exchange
version: 0.1.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.8.0'
  query:
    name: '@subql/query'
    version: '>=1.5.0'
description: >-
  This project is for capturing the data for the exchange contract on the
  subquery kepler network
repository: 'https://github.com/subquery/subquery-network-exchange.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527' #moonbase alpha
  endpoint: 'wss://moonbeam-alpha.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'

x-frontier: &frontier
  kind: substrate/FrontierEvm
  startBlock: 2721778 
  processor: &frontier-processor
    file: './dist/frontierEvm.js'
  assets: 
    permissionedExchange:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/PermissionedExchange.sol/PermissionedExchange.json
    rewardsDistributor:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/RewardsDistributer.sol/RewardsDistributer.json

dataSources:
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: permissionedExchange
        address: '0x86a107Cceb1aAD40b6f457878DAdbbe66ef0C1DA'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleExchangeOrderSent
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - ExchangeOrderSent(uint256 indexed orderId, address sender, address tokenGive, address tokenGet, uint256 amountGive, uint256 amountGet, uint256 expireDate)
        - handler: handleTrade
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Trade(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet) 
        - handler: handleOrderSettled
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - OrderSettled(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet)
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: rewardsDistributor
        address: '0x16Ea9AEF51e28e8f84D87b8667f8e7103804061b'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRewardsClaimed
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - ClaimRewards(address indexed indexer, address indexed delegator, uint256 rewards)
