specVersion: 1.0.0
name: subquery-network-exchange
version: 0.1.0
runner:
  node:
    name: '@subql/node-ethereum'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Exchange project on the SubQuery Kepler Testnet
repository: 'https://github.com/subquery/subquery-network-exchange.git'
schema:
  file: ./schema.graphql
network:
  chainId: '80001' # Mumbai testnet 
  endpoint: 'https://polygon-mumbai.g.alchemy.com/v2/olBcbaUN-00iYo-4VDlJYbkpCmj5rLY0'
  dictionary: 'https://mumbai-dict-cr.api.onfinality.io'

x-ethereum: &ethereum
  kind: ethereum/Runtime 
  startBlock: 32470803 
  assets: 
    permissionedExchange:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/PermissionedExchange.sol/PermissionedExchange.json

dataSources:
  - <<: *ethereum
    options:
      abi: permissionedExchange
      address: '0x4927Cf539738D619ceAeA674781a679CC373861D'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleExchangeOrderSent
          kind: ethereum/LogHandler
          filter:
            topics:
              - ExchangeOrderSent(uint256 indexed orderId, address sender, address tokenGive, address tokenGet, uint256 amountGive, uint256 amountGet, uint256 expireDate)
        - handler: handleTrade
          kind: ethereum/LogHandler
          filter:
            topics:
              - Trade(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet) 
        - handler: handleOrderSettled
          kind: ethereum/LogHandler
          filter:
            topics:
              - OrderSettled(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet)
        - handler: handleQuotaAdded
          kind: ethereum/LogHandler
          filter:
            topics:
              - QuotaAdded(address token, address account, uint256 amount)