specVersion: 1.0.0
name: subquery-network-exchange
version: 0.1.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project is for capturing the data for the exchange contract on the
  subquery kepler network
repository: 'https://github.com/subquery/subquery-network-exchange.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0x5c562e6300954998233c9a40b6b86f3028977e6d32d0da1af207738d19f98c1b'
  endpoint: 'wss://mandala-tc7-rpcnode.aca-dev.network/ws'
  dictionary: 'https://api.subquery.network/sq/subquery/acala-mandala-tc7-dictionary'

x-frontier: &frontier
  kind: substrate/AcalaEvm
  startBlock: 1398237 
  processor: &frontier-processor
    file: './dist/acalaEvm.js'
  assets: 
    permissionedExchange:
      file: ./node_modules/@subql/contract-sdk/artifacts/contracts/ServiceAgreementRegistry.sol/PermissionedExchange.json

dataSources:
  - <<: *frontier
    processor:
      <<: *frontier-processor
      options:
        abi: permissionedExchange
        address: '0x8eE5f75281F9AA28f8A866875F46D923Bc7Bc9a4'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: 
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - ExchangeOrderSent(uint256 indexed orderId, address sender, address tokenGive, address tokenGet, uint256 amountGive, uint256 amountGet, uint256 expireDate)
        - handler: 
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - Trade(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet) 
        - handler: 
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - OrderSettled(uint256 indexed orderId, address tokenGive, uint256 amountGive, address tokenGet, uint256 amountGet)
